<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bs2log</string>
	</array>
	<key>name</key>
	<string>BS2000 Access Log</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#nonprintables</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=^.{21})(..)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.bs2log</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.entry.bs2log</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#nonprintables</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^.{10})(T)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.bs2log</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.bs2log</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\d\d\:\d\d\:\d\d)(Z)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.bs2log</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.double-slash.bs2log</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.timestamp.bs2log</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>nonprintables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>support.constant.bs2log</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.bs2log</string>
	<key>uuid</key>
	<string>f3de1996-6925-46f3-8dad-49d799c725c3</string>
</dict>
</plist>
