<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ufa</string>
	</array>
	<key>name</key>
	<string>UNIFA-Trace</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>.*Exception.*</string>
			<key>name</key>
			<string>invalid.illegal.unifatrace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=^.{54}).*</string>
			<key>name</key>
			<string>string.unquoted.unifatrace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s{6}.*</string>
			<key>name</key>
			<string>string.unquoted.unifatrace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=^.{32})\S{1,17}</string>
			<key>name</key>
			<string>storage.type.unifatrace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=^.{4}\d\s)([a-z]){2}anw[0-9]{3}</string>
			<key>name</key>
			<string>constant.other.unifatrace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=^.{4}\d\s)\w*</string>
			<key>name</key>
			<string>constant.numeric.unifatrace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^.{4}\d</string>
			<key>name</key>
			<string>comment.line.double-slash.unifatrace</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=(.{49}))\d{2,4}(?=[ ])</string>
			<key>name</key>
			<string>comment.line.double-slash.unifatrace</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.unifatrace</string>
	<key>uuid</key>
	<string>2d7e8365-b522-4a62-9b63-bc737425ae61</string>
</dict>
</plist>
